% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Rapport},
  pdfauthor={La Vague},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Rapport}
\author{La Vague}
\date{2026-04-19}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\newpage

\section{Introduction}\label{introduction}

Qui n'a jamais débattu avec ses amis pour savoir quel jeu vidéo est le
meilleur de tous les temps ? Entre les fans de LOL \emph{(quelle
idée\ldots)}, les nostalgiques de Mario et les adeptes de Minecraft, les
opinions sont souvent\ldots{} très tranchées.

Mais le jeu vidéo ne se résume pas uniquement à ses ventes : derrière
chaque succès commercial se cache aussi une communauté de joueurs,
parfois très engagée. Certains terminent un jeu\ldots{} d'autres
cherchent à le finir le plus vite possible.

Dans ce projet, nous avons choisi de croiser deux aspects
complémentaires du jeu vidéo :

\begin{itemize}
\tightlist
\item
  les \textbf{performances commerciales} avec le dataset \textbf{Video
  Game Sales} ;
\item
  l'\textbf{activité compétitive et communautaire} avec le dataset
  \textbf{Speedrun.com Data}, qui recense les records, les joueurs et
  les catégories de speedrun.
\end{itemize}

L'objectif est de ne pas se limiter à une vision économique du jeu
vidéo, mais d'explorer également l'engagement des joueurs. En combinant
ces deux sources, nous cherchons à comprendre si les jeux les plus
vendus sont aussi ceux qui génèrent le plus d'activité dans la
communauté, ou si, au contraire, certains jeux deviennent cultes
indépendamment de leur succès commercial.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Données}\label{donnuxe9es}

Dans le cadre de ce projet, nous utilisons deux jeux de données
complémentaires afin d'analyser à la fois le \textbf{succès commercial}
des jeux vidéo et leur \textbf{engagement au sein de la communauté}.

\subsection{Dataset 1 : Video Game Sales (Rush
Kirubi)}\label{dataset-1-video-game-sales-rush-kirubi}

Ce dataset combine des données de ventes issues de
\href{https://www.vgchartz.com/}{\textbf{VGChartz}} et des scores/avis
issus de \href{https://www.metacritic.com/}{\textbf{Metacritic}}.

Il est important de noter que le fichier date du \textbf{22 décembre
2016}, et ne contient donc pas des données récentes.

Le fichier principal est un \textbf{CSV}
(\emph{Video\_Games\_Sales\_as\_at\_22\_Dec\_2016.csv}), de dimension
\textbf{(16 719 × 16)}.

Cependant, le jeu de données présente de nombreuses valeurs manquantes,
notamment pour les variables liées aux scores utilisateurs. En effet, la
plateforme Metacritic ne couvre pas toutes les plateformes présentes
dans le dataset. Ainsi, environ \textbf{9 600 observations} disposent de
données complètes.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Dictionnaire de variables et qualité
attendue}\label{dictionnaire-de-variables-et-qualituxe9-attendue}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1557}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3443}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0738}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0656}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0738}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2869}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Colonne
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Nature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Type
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\% NA
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Uniques
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Exemples
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Name & qualitative nominale (texte) & object & 0.02\% & 11 563 & Wii
Sports; Super Mario Bros. \\
Platform & qualitative nominale (catégorie) & object & 0.00\% & 31 &
Wii; NES \\
Year\_of\_Release & quantitative discrète (année) & float64 & 1.61\% &
--- & 2006.0; 1985.0 \\
Genre & qualitative nominale (catégorie) & object & 0.02\% & 12 &
Sports; Platform \\
Publisher & qualitative nominale (catégorie) & object & 0.32\% & 582 &
Nintendo \\
NA\_Sales & quantitative continue (millions) & float64 & 0.00\% & --- &
41.36; 29.08 \\
EU\_Sales & quantitative continue (millions) & float64 & 0.00\% & --- &
28.96; 3.58 \\
JP\_Sales & quantitative continue (millions) & float64 & 0.00\% & --- &
3.77; 6.81 \\
Other\_Sales & quantitative continue (millions) & float64 & 0.00\% & ---
& 8.45; 0.77 \\
Global\_Sales & quantitative continue (millions) & float64 & 0.00\% &
--- & 82.53; 40.24 \\
Critic\_Score & quantitative discrète (0--100) & float64 & 51.33\% & ---
& 76.0; 82.0 \\
Critic\_Count & quantitative discrète (compte) & float64 & 51.33\% & ---
& 51.0; 73.0 \\
User\_Score & quantitative continue (0--10 + ``tbd'') & object & 40.10\%
& 96 & 8; 8.3; tbd \\
User\_Count & quantitative discrète (compte) & float64 & 54.60\% & --- &
322.0; 709.0 \\
Developer & qualitative nominale (catégorie) & object & 39.61\% & 1 696
& Nintendo \\
Rating & qualitative (catégorie ESRB) & object & 40.49\% & 8 & E \\
\end{longtable}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Remarques}\label{remarques}

\begin{itemize}
\tightlist
\item
  La variable \texttt{Platform} est codée sous forme d'abréviations (par
  exemple \texttt{PS4}, \texttt{GB}, \texttt{X360}). La correspondance
  complète est fournie en \textbf{Annexe A}.
\item
  Les scores critiques de Metacritic sont sur une échelle de 0 à 100\\
\item
  De nombreuses données liées aux scores sont manquantes, mais le volume
  restant reste suffisant pour mener des analyses pertinentes
\item
  Les variables \textbf{User\_Score} et \textbf{Year\_of\_Release}
  contiennent des valeurs non numériques (\emph{tbd}, \emph{N/A}),
  nécessitant un nettoyage préalable
\item
  Chaque ligne correspond à un \textbf{jeu sur une plateforme donnée}.
  Ainsi, un même jeu peut apparaître plusieurs fois, ce qui peut biaiser
  certaines analyses si l'on ne précise pas l'unité d'étude
\item
  Les noms de développeurs, éditeurs ou plateformes peuvent présenter
  des variations (abréviations, doublons), ce qui nécessite un travail
  de normalisation, notamment pour le croisement avec d'autres datasets
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Unité d'observation et
sous-groupes}\label{unituxe9-dobservation-et-sous-groupes}

L'unité d'observation est le couple \textbf{(jeu, plateforme)} : un même
titre peut apparaître plusieurs fois s'il est sorti sur différentes
plateformes.

Cela permet de définir plusieurs sous-groupes :

\begin{itemize}
\tightlist
\item
  \textbf{Plateforme} (≈ 31 plateformes)\\
\item
  \textbf{Genre} (≈ 12 catégories)\\
\item
  \textbf{Région de vente} (NA, EU, JP, Other)\\
\item
  \textbf{Rating ESRB} (classification par âge)
\end{itemize}

Ces dimensions structurent fortement les analyses possibles.

\subsection{Dataset 2 : Speedrun.com
Dataset}\label{dataset-2-speedrun.com-dataset}

Ce dataset recense les jeux référencés sur
\href{https://www.speedrun.com/}{\textbf{Speedrun.com}}, la plateforme
de référence pour le speedrunning. Il fournit pour chaque jeu des
métadonnées générales ainsi que l'ensemble des runs validées et classées
sur la plateforme.

Le dataset est composé de \textbf{4 fichiers CSV} reliés entre eux par
des identifiants communs :

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1880}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1278}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1579}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.5263}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Fichier
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Dimensions
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Unité d'observation
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Description
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\emph{games-data.csv} & (43 663 × 6) & Jeu & Métadonnées de chaque jeu
référencé sur Speedrun.com \\
\emph{leaderboards-data.csv} & (2 232 884 × 3) & Run classée & Runs
validées et classées sur les leaderboards \\
\emph{platforms-data.csv} & (213 × 3) & Plateforme & Table de référence
des plateformes (consoles, PC, supports mobiles) \\
\emph{genres-data.csv} & (2 380 × 2) & Genre & Table de référence des
genres de jeu \\
\end{longtable}

Le dataset couvre des jeux dont les dates de sortie s'étendent de
\textbf{1971 à 2026} (dates futures correspondant à des jeux annoncés),
et dont l'ajout sur la plateforme Speedrun.com s'échelonne de
\textbf{fin 2014 à début 2025}. Les runs enregistrées couvrent la
période \textbf{2012-2025}.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{Fichier principal :
\emph{games-data.csv}}{Fichier principal : games-data.csv}}\label{fichier-principal-games-data.csv}

Fichier central du dataset. Chaque ligne correspond à un jeu unique
référencé sur Speedrun.com.

\paragraph{Dictionnaire de variables}\label{dictionnaire-de-variables}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1200}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3760}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0640}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0640}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0720}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3040}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Colonne
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Nature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Type
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\% NA
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Uniques
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Exemples
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
gameId & qualitative nominale (identifiant unique) & string & 0.00\% &
43 662 & j1n8nj91 ; m1zqmo76 \\
gameName & qualitative nominale (texte) & string & 0.00\% & 43 639 &
Super Mario 64 ; Celeste \\
releaseDate & quantitative discrète (date) & string & 0.00\% & 9 958 &
01/11/1971 ; 01/01/2020 \\
createdDate & quantitative discrète (horodatage ISO 8601) & string &
1.80\% & 42 865 & 2022-10-11T15:53:28Z \\
platforms & qualitative nominale (liste d'identifiants) & string &
6.50\% & 4 874 & vm9vn63k ; o7e25xew,v06ddw64 \\
genres & qualitative nominale (liste d'identifiants) & string & 66.60\%
& 4 878 & \emph{(identifiants vers genres-data)} \\
\end{longtable}

\paragraph{Remarques}\label{remarques-1}

\begin{itemize}
\tightlist
\item
  \textbf{releaseDate} est stockée au format \emph{JJ/MM/AAAA} et devra
  être convertie en véritable date lors du nettoyage ;
  \textbf{createdDate} est au format ISO 8601 (norme internationale de
  date et heure)
\item
  Les colonnes \textbf{platforms} et \textbf{genres} contiennent des
  \textbf{listes d'identifiants séparés par des virgules}, qui renvoient
  vers les fichiers \emph{platforms-data.csv} et \emph{genres-data.csv}
  ; il faudra séparer ces listes en plusieurs lignes (une ligne par
  plateforme ou par genre) avant de pouvoir faire les jointures, en
  utilisant la fonction \textbf{\texttt{separate\_rows()}} du package
  \textbf{tidyr}
\item
  Le taux élevé de valeurs manquantes sur \textbf{genres} (67\%) reflète
  le caractère optionnel de cette métadonnée sur Speedrun.com, et non
  une lacune du dataset
\item
  \textbf{gameName} servira de clé de jointure avec le dataset Video
  Game Sales, après un travail de normalisation des noms (différences de
  ponctuation, d'écriture, versions, etc.)
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{Fichier des runs classées :
\emph{leaderboards-data.csv}}{Fichier des runs classées : leaderboards-data.csv}}\label{fichier-des-runs-classuxe9es-leaderboards-data.csv}

Contient toutes les runs \textbf{validées} et classées sur les
leaderboards Speedrun.com. C'est le fichier de référence pour mesurer
l'activité communautaire autour de chaque jeu.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0882}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.5392}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0784}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0686}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1078}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1176}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Colonne
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Nature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Type
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\% NA
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Uniques
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Exemples
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
runId & qualitative nominale (identifiant unique) & string & 0.00\% & 2
232 884 & zpg4gdnz \\
gameId & qualitative nominale (identifiant vers games-data) & string &
0.00\% & 42 278 & j1n8nj91 \\
players & qualitative nominale (liste d'identifiants de joueurs) &
string & 3.90\% & 480 808 & 8d4kdg58 \\
\end{longtable}

\paragraph{Remarques}\label{remarques-2}

\begin{itemize}
\tightlist
\item
  Les indicateurs d'activité utilisés dans l'analyse (\textbf{runCount}
  et \textbf{playerCount}) ne sont pas présents directement et devront
  être calculés en regroupant les runs par jeu :

  \begin{itemize}
  \tightlist
  \item
    \textbf{runCount} : nombre total de runs par jeu
  \item
    \textbf{playerCount} : nombre de joueurs uniques par jeu
  \end{itemize}
\item
  La colonne \textbf{players} peut contenir plusieurs identifiants
  séparés par des virgules dans le cas de runs réalisées en coopération
\item
  \textbf{3.9\%} des runs n'ont pas d'information sur les joueurs (runs
  anonymes ou comptes utilisateurs supprimés)
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{Table de référence :
\emph{platforms-data.csv}}{Table de référence : platforms-data.csv}}\label{table-de-ruxe9fuxe9rence-platforms-data.csv}

Liste des plateformes de jeu (consoles, ordinateurs, supports mobiles)
référencées sur Speedrun.com.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1271}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3814}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0678}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0593}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0763}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2881}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Colonne
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Nature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Type
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\% NA
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Uniques
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Exemples
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
platformId & qualitative nominale (identifiant unique) & string & 0.00\%
& 213 & jm951reo \\
name & qualitative nominale (texte) & string & 0.00\% & 213 & 2DS ;
Nintendo Switch ; PC \\
releaseYear & quantitative discrète (année) & int64 & 0.00\% & 53 & 2013
; 2017 \\
\end{longtable}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{Table de référence :
\emph{genres-data.csv}}{Table de référence : genres-data.csv}}\label{table-de-ruxe9fuxe9rence-genres-data.csv}

Liste des genres de jeu référencés sur Speedrun.com.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0796}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3982}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0708}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0619}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0796}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3097}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Colonne
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Nature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Type
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\% NA
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Uniques
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Exemples
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
genreId & qualitative nominale (identifiant unique) & string & 0.00\% &
2 380 & l2kodwn1 \\
name & qualitative nominale (texte) & string & 0.00\% & 2 380 &
Platformer ; RPG ; .io Game \\
\end{longtable}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Relations entre les
fichiers}\label{relations-entre-les-fichiers}

Le dataset est organisé autour du fichier central \emph{games-data.csv}
:

\begin{verbatim}
leaderboards-data ── games-data ── platforms-data
                         │
                         └──────── genres-data
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Le fichier \emph{leaderboards-data.csv} est relié à
  \emph{games-data.csv} par la colonne \textbf{gameId} ; après
  agrégation, il fournit les indicateurs d'activité par jeu
\item
  Les fichiers \emph{platforms-data.csv} et \emph{genres-data.csv} sont
  des \textbf{tables de référence} : ils permettent de traduire les
  identifiants présents dans les colonnes \textbf{platforms} et
  \textbf{genres} de \emph{games-data.csv} en noms lisibles (par
  exemple, transformer \emph{vm9vn63k} en \emph{Nintendo 64})
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Remarques transversales}\label{remarques-transversales}

\begin{itemize}
\tightlist
\item
  Tous les identifiants (gameId, runId, platformId, genreId) sont des
  \textbf{codes alphanumériques de 8 caractères} propres à Speedrun.com
  ; ils n'ont pas de signification en eux-mêmes mais servent uniquement
  à relier les fichiers entre eux
\item
  Le fichier \emph{leaderboards-data.csv} représente l'essentiel du
  volume du dataset (environ 2.2 millions de lignes) et devra être
  \textbf{agrégé par jeu} dès la phase de préparation des données
\item
  La distribution de l'activité est très asymétrique : une minorité de
  jeux concentre la grande majorité des runs (\emph{Super Mario 64},
  \emph{Celeste}, \emph{Minecraft}, \emph{Super Mario Odyssey}), tandis
  que de nombreux jeux ont très peu voire aucune run soumise
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Unité d'observation et
sous-groupes}\label{unituxe9-dobservation-et-sous-groupes-1}

L'unité d'observation dépend du fichier : le \textbf{jeu}
(\emph{games-data.csv}) ou la \textbf{run}
(\emph{leaderboards-data.csv}). Après agrégation des runs par jeu,
l'unité d'analyse principale devient le \textbf{jeu}.

Les sous-groupes exploitables sont :

\begin{itemize}
\tightlist
\item
  \textbf{Période de sortie} (par décennie ou par année, via conversion
  de \texttt{releaseDate})
\item
  \textbf{Ancienneté sur la plateforme} (via \texttt{createdDate}, pour
  analyser la dynamique d'adoption)
\item
  \textbf{Niveau d'activité} (en regroupant les jeux selon leur nombre
  de runs ou de joueurs, par exemple : faible, moyen, élevé)
\item
  \textbf{Plateforme} (après séparation des listes dans
  \texttt{platforms} et jointure avec \emph{platforms-data.csv})
\item
  \textbf{Genre} (après séparation des listes dans \texttt{genres} et
  jointure avec \emph{genres-data.csv})
\end{itemize}

\newpage

\section{Annexes}\label{annexes}

\subsection{Annexe A --- Correspondance des codes de
plateformes}\label{annexe-a-correspondance-des-codes-de-plateformes}

Dans le dataset \emph{Video Game Sales}, la variable \texttt{Platform}
est codée sous forme d'abréviations. Afin de faciliter la lecture du
rapport, le tableau ci-dessous présente la correspondance entre les
codes utilisés et le nom complet des plateformes.

\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
Code & Plateforme \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2600 & Atari 2600 \\
3DO & 3DO Interactive Multiplayer \\
3DS & Nintendo 3DS \\
DC & Dreamcast \\
DS & Nintendo DS \\
GB & Game Boy \\
GBA & Game Boy Advance \\
GC & Nintendo GameCube \\
GEN & Sega Genesis / Mega Drive \\
GG & Game Gear \\
N64 & Nintendo 64 \\
NES & Nintendo Entertainment System \\
NG & Neo Geo \\
PC & PC \\
PCFX & PC-FX \\
PS & PlayStation \\
PS2 & PlayStation 2 \\
PS3 & PlayStation 3 \\
PS4 & PlayStation 4 \\
PSP & PlayStation Portable \\
PSV & PlayStation Vita \\
SAT & Sega Saturn \\
SCD & Sega CD \\
SNES & Super Nintendo Entertainment System \\
TG16 & TurboGrafx-16 \\
WS & WonderSwan \\
Wii & Nintendo Wii \\
WiiU & Nintendo Wii U \\
X360 & Xbox 360 \\
XB & Xbox \\
XOne & Xbox One \\
\end{longtable}

\newpage

\section{Analyse des ventes}\label{analyse-des-ventes}

\subsection{1. Quelles plateformes ont généré le plus de ventes à
l'échelle mondiale
?}\label{quelles-plateformes-ont-guxe9nuxe9ruxe9-le-plus-de-ventes-uxe0-luxe9chelle-mondiale}

Dans l'optique de concevoir et de commercialiser le jeu parfait, nous
débutons par une étude du marché : quelles plateformes ont généré le
plus de ventes à l'échelle mondiale ? Identifier les machines dominantes
nous indiquera sur quel support viser pour maximiser l'audience
potentielle de notre jeu. Nous supposons que le marché est
historiquement écrasé par quelques consoles phares de constructeurs
majeurs (Sony, Nintendo), mais nous nous demandons si cette domination
se concentre sur une ou deux machines, ou si elle se répartit entre les
différentes générations.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-5-1.pdf}}

Le marché ne suit pas une logique équilibrée mais une logique de paliers
dominée par deux acteurs historiques. Sony s'impose en volume, porté par
le succès titanesque de la PS2 et par la présence de toute sa gamme de
salon (PS1, PS3, PS4) en haut du classement. Nintendo se distingue lui
par l'étendue de son catalogue de machines et une longévité remarquable,
là où Sega n'a pas su durer dans le temps. Pour notre jeu,
l'enseignement est direct : viser un support à très large parc installé,
typiquement une console Sony ou Nintendo de sa génération, conditionne
fortement l'audience commerciale atteignable --- un lancement sur une
plateforme marginale partirait avec un handicap structurel.

\newpage

\subsection{2. Quelles sont les plateformes qui ont générées le plus de
ventes par région
?}\label{quelles-sont-les-plateformes-qui-ont-guxe9nuxe9ruxe9es-le-plus-de-ventes-par-ruxe9gion}

Dans la continuité de l'analyse précédente, nous affinons notre étude de
marché à l'échelle régionale : les plateformes dominantes au niveau
mondial le sont-elles partout ? La réponse conditionne le choix du
support selon le marché que notre jeu cherchera à conquérir. Nous
supposons que les préférences des joueurs varient d'une région à
l'autre, en fonction des habitudes culturelles et de la présence
historique des constructeurs, et cherchons donc à identifier les
plateformes dominantes en Amérique du Nord, en Europe, au Japon et dans
les autres régions.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-6-1.pdf}}

Les graphiques révèlent des marchés aux logiques nettement distinctes.
Les régions occidentales se ressemblent, l'Amérique du Nord penche vers
Microsoft (Xbox 360) tout en restant solidement Sony, l'Europe est plus
franchement Sony et se singularise par un PC bien plus présent
qu'ailleurs, tandis que le Japon fonctionne en circuit quasi fermé,
dominé par les consoles Nintendo et notamment les portables, Microsoft
et le PC y étant marginaux. Les autres régions s'alignent sur le modèle
européen.

Pour notre jeu, l'enseignement est qu'il n'existe pas de support
universel : le choix dépend du marché ciblé. Une stratégie
multiplateforme (Sony, Xbox, PC) couvre efficacement l'Occident, mais
toucher le Japon imposerait une présence sur l'écosystème Nintendo, à
contre-courant de nos autres marchés. La force singulière du PC en
Europe est par ailleurs à noter, d'autant qu'elle recoupe la plateforme
reine du speedrun que nous identifierons plus loin.

\newpage

\subsection{3. Quels sont les genres de jeux vidéo qui génèrent le plus
de ventes au niveau mondiale
?}\label{quels-sont-les-genres-de-jeux-viduxe9o-qui-guxe9nuxe8rent-le-plus-de-ventes-au-niveau-mondiale}

L'objectif ici est d'identifier les \textbf{genres} qui génèrent le plus
de ventes à l'échelle mondiale. On peut s'attendre à ce que certains
genres plus ``populaires'', comme les jeux d'action ou de sport,
dominent le marché.

NB : Lors de l'analyse exploratoire, un problème est apparu : deux
lignes contenaient une valeur manquante (\texttt{NA}) pour la variable
\emph{Genre}, ce qui créait une catégorie artificielle représentant
\textbf{2.42 millions de ventes globales}. Ces lignes ont été supprimées
afin de ne pas fausser les résultats.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-7-1.pdf}}

Le graphique met en évidence le \textbf{top 3 des genres les plus
vendeurs} :

\begin{itemize}
\item
  \textbf{Action}
\item
  \textbf{Sports}
\item
  \textbf{Shooter}
\end{itemize}

Ces genres dominent clairement les ventes globales, ce qui confirme
qu'ils sont les plus populaires auprès du grand public. À l'inverse, des
genres comme \textbf{Strategy} ou \textbf{Puzzle} restent plus niche et
génèrent moins de ventes.

\newpage

\subsection{4. Quelle région (Amérique du Nord, Europe, Japon, autres
régions) contribue le plus aux ventes de jeux vidéo ?}\label{q4-regions}

Pour répondre à cette question, nous avons utilisé un diagramme en
barres. Ce type de graphique est particulièrement adapté pour comparer
des quantités entre plusieurs catégories distinctes, ici les différentes
régions du monde : Amérique du Nord, Europe, Japon et autres régions.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-8-1.pdf}}

L'\textbf{Amérique du Nord} domine largement les ventes de jeux vidéo,
représentant la plus grande part du marché. Elle est suivie par
l'\textbf{Europe}, tandis que le Japon et les autres régions contribuent
beaucoup moins. Cela montre que l'industrie des jeux vidéos est
principalement portée par les marchés occidentaux.

\newpage

\subsection{5. Quels sont les jeux les plus vendus globalement
?}\label{quels-sont-les-jeux-les-plus-vendus-globalement}

Après avoir étudié la structure globale du marché du jeu vidéo --- en
identifiant les régions dominantes, les genres les plus populaires et
les plateformes les plus performantes --- il est pertinent de
s'intéresser aux \textbf{jeux eux-mêmes}.

En effet, ces analyses nous ont permis de comprendre \emph{où} et
\emph{comment} se réalisent les ventes. Nous cherchons désormais à
identifier \textbf{quels jeux concentrent réellement ce succès} à
l'échelle mondiale.

Pour cela, nous avons agrégé les ventes par \textbf{nom de jeu}, afin
d'éviter les doublons liés aux différentes plateformes, puis extrait le
\textbf{top 10 des jeux les plus vendus dans le monde}.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-9-1.pdf}}

L'analyse du classement mondial met en évidence la domination de
quelques titres emblématiques, souvent issus de \textbf{franchises
majeures} (comme \emph{Mario} ou \emph{Grand Theft Auto}). Ces jeux
bénéficient d'une forte reconnaissance internationale, d'un marketing
important et d'une présence sur des consoles très populaires.

On observe également que plusieurs de ces jeux sont associés à des
\textbf{consoles à très fort succès}, notamment celles de Nintendo
(comme la Wii), ce qui confirme les résultats obtenus précédemment sur
la domination de certaines plateformes.

Ainsi, le succès global d'un jeu apparaît comme le résultat d'une
combinaison de facteurs : popularité du genre, diffusion de la
plateforme et portée internationale de la licence.

\newpage

\subsection{6. Observe-t-on des différences régionales dans les
préférences de plateformes ou de genres ?}\label{q6-differences}

Pour orienter le genre de notre futur jeu, nous examinons si les
préférences des joueurs varient selon les régions (Amérique du Nord,
Europe, Japon, autres) : un genre porteur sur un marché ne l'est pas
nécessairement ailleurs, ce qui pèse sur le positionnement à adopter.
Nous formulons l'hypothèse suivante : le Japon privilégierait les jeux
de rôle (RPG), tandis que l'Amérique du Nord et l'Europe seraient plus
orientées vers l'action ou le sport. Pour la tester, nous comparons les
ventes par genre selon les régions.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-10-1.pdf}}

Le graphique confirme l'hypothèse et oppose deux modèles de marché.
L'Occident, Amérique du Nord et Europe aux profils très proches, aiment
les genres d'action et de compétition (Action, Sports, Shooter),
l'Amérique du Nord menant simplement en volume. Le Japon suit une
logique inverse, nettement tourné vers les RPG et les expériences
narratives, là où Shooter et Sports restent secondaires. Les autres
régions s'alignent sur le modèle occidental.

Pour notre jeu, l'enseignement rejoint celui des plateformes : il n'y a
pas de genre universel. Un jeu d'action ou de sport viserait
naturellement les grands marchés occidentaux, mais resterait peu adapté
au Japon, qui exigerait un positionnement narratif.

Cibler simultanément ces marchés suppose donc un genre suffisamment
hybride, ou un choix assumé de concentrer nos efforts sur l'Occident
(d'autant que c'est là, nous le verrons, que se trouve aussi l'essentiel
de la communauté speedrun.)

\newpage

\subsection{7. Quelles sont les préférences régionales en termes de jeux
?}\label{quelles-sont-les-pruxe9fuxe9rences-ruxe9gionales-en-termes-de-jeux}

Après les genres et les plateformes, nous descendons au niveau des jeux
eux-mêmes pour affiner notre étude de marché : les titres les plus
populaires mondialement dominent-ils partout, ou des préférences locales
émergent-elles région par région ? La réponse nous dit dans quelle
mesure un même jeu peut s'imposer sur tous nos marchés cibles. Pour
cela, nous avons agrégé les ventes par jeu et par région, puis extrait
le top 10 de chacune, présenté en facettes pour comparer les
classements.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-11-1.pdf}}

L'analyse prolonge directement les constats précédents. L'Amérique du
Nord et l'Europe partagent largement les mêmes têtes de classement, des
jeux grand public issus de grandes franchises internationales,
confirmant la proximité de ces deux marchés occidentaux. Le Japon, lui,
se referme sur des licences locales, essentiellement Nintendo (Pokémon,
Super Mario), en cohérence avec sa préférence marquée pour les RPG.

Pour notre jeu, l'enseignement est qu'un succès mondial ne se décrète
pas par la seule qualité : il se heurte à des attentes culturelles
ancrées. Conquérir l'Occident reste accessible à un titre international
bien positionné, alors que le marché japonais, structuré autour de
franchises locales établies, est quasi imprenable pour un nouveau venu.
Cela renforce le choix de concentrer nos ambitions sur les marchés
occidentaux, qui sont à la fois les plus accessibles commercialement et
le cœur de la communauté speedrun.

\newpage

\section{Analyse de Speedrun.com}\label{analyse-de-speedrun.com}

\subsection{8. Quels sont les jeu avec le plus de runs
?}\label{quels-sont-les-jeu-avec-le-plus-de-runs}

Après avoir étudié en profondeur les ventes de jeux vidéo à l'échelle
mondiale, nous allons nous intéresser au nombre de runs de speedrun que
chacun des jeux possède sur le site speedrun.com.

Notre objectif est de savoir quels sont les plus speedrunnés afin
d'avoir une idée du style de jeux que la communauté apprécie relancer.

Nous imaginons que le nombre de runs le plus élevé sera atteint par des
jeux très connus, du style Mario Bros ou Minecraft par exemple, des jeux
connus dans le monde entier.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-12-1.pdf}}

À la lecture du graphique, nous nous rendons compte que la popularité du
jeu ne suffit pas pour en faire un jeu très speedrunné, car beaucoup de
jeux qu'on ne considère pas comme des « classiques » du jeu vidéo sont
présents dans ce classement, notamment Diddy Kong Racing (un clone de
Mario Kart) ou encore PAYDAY 2 (un FPS coopératif). Un jeu peu connu
peut être speedrunné s'il a les bons atouts, notamment un format adapté
(durée d'une run, accessibilité, mécaniques répétables) comme les jeux
de course ou de plateforme. Cependant, au vu de la grande quantité de
jeux connus dans le classement, nous aurions plus de chances de produire
un jeu speedrunné s'il est très populaire.Notre objectif est donc de
concevoir un jeu populaire avec de bonnes mécaniques de speedrun.

\newpage

\subsection{9. Quels sont les genres de jeu avec le plus de runs
?}\label{quels-sont-les-genres-de-jeu-avec-le-plus-de-runs}

Après avoir identifié les jeux les plus speedrunnés, nous souhaitons
élargir l'analyse aux genres qui rassemblent le plus de runs sur
speedrun.com.

Au vu des caractéristiques propres au speedrun (rejouabilité, sessions
courtes), nous imaginons que les genres dominants seront les jeux de
plateforme et les les jeux de courses, au détriment des RPG ou des jeux
de stratégie, qui impliquent des parties beaucoup plus longues.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-13-1.pdf}}

À la lecture de ce graphique, le platformer semble être le genre de jeu
le plus relancé par les joueurs, loin devant les jeux de course et les
FPS. En effet, les jeux de plateforme se prêtent bien, comme nous
l'avons vu précédemment, aux mécaniques de rejouabilité. Si on veut que
notre jeu se classe parmi les plus speedrunnés, il peut être intéressant
qu'il mélange les styles. Nous pouvons imaginer un platformer sous forme
de course.

\newpage

\subsection{10. L'année de sortie est-elle corrélée au nombre de runs
des jeux
?}\label{lannuxe9e-de-sortie-est-elle-corruxe9luxe9e-au-nombre-de-runs-des-jeux}

L'année de sortie pourrait avoir un impact sur le nombre de runs par
jeu. Même si cette information ne nous indiquera pas directement quand
sortir notre jeu, elle peut révéler quelles époques (et donc quels
thèmes de jeu dominants) incitent le plus les joueurs à relancer une
partie pour battre des records.

Nous imaginons que les jeux les plus anciens seront les plus
speedrunnés, étant donné qu'ils auront eu plus de temps pour se faire
connaître.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-14-1.pdf}}
Étonnamment, nous remarquons un pic du nombre de runs pour les jeux
sortis autour de 2014. Cela pourrait s'expliquer par l'essor du
streaming sur Twitch durant cette période, qui a donné au speedrun une
visibilité nouvelle et incité les joueurs à revenir sur leurs jeux pour
battre des records. À cela s'ajoute une évolution dans la conception des
jeux eux-mêmes, de plus en plus pensés pour la rejouabilité et le
speedrun, avec des mécaniques comme les chronomètres intégrés, les
classements en ligne ou les niveaux découpés en segments courts.

Notre jeu devra donc s'inscrire dans un univers récent et être
facilement partageable sur les plateformes de streaming.

\newpage

\subsection{11. Quelles sont les plateformes les plus speedrunnées
?}\label{quelles-sont-les-plateformes-les-plus-speedrunnuxe9es}

La question est cruciale : il nous faut choisir la bonne plateforme pour
sortir notre jeu, car un jeu lancé sur une plateforme peu active aura du
mal à fédérer une communauté de speedrun. Nous imaginons que la
plateforme la plus speedrunnée sera le PC, son caractère universel le
rendant accessible au plus grand nombre.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-15-1.pdf}}
Comme attendu, le PC domine largement devant toutes les autres
plateformes. C'est en effet une plateforme qui permet facilement
d'enregistrer et de soumettre des runs sur speedrun.com (ce qui peut
d'ailleurs constituer un biais en faveur des jeux PC dans notre
dataset). Quoi qu'il en soit, notre jeu devra être disponible sur PC
pour maximiser ses chances d'être speedrunné.

\newpage

\subsection{12. Combien de temps dure le speedrun d'un jeu complet
?}\label{combien-de-temps-dure-le-speedrun-dun-jeu-complet}

Après avoir identifié les genres et plateformes propices au speedrun,
nous nous intéressons à un paramètre de conception central : la durée
d'une run. Cette information est directement actionnable pour notre jeu,
car la longueur d'une partie conditionne sa rejouabilité

Nous imaginons que la majorité des runs se concentrent sur une durée
modérée, de l'ordre de quelques dizaines de minutes, plutôt que sur des
parties très longues qui limiteraient le nombre de tentatives.
\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-16-1.pdf}}

L'essentiel des runs est compris entre 10 minutes et 2 heures. Les runs
de quelques secondes ou de plus de 10 heures restent marginaux.

Cette durée nous donne une cible concrète pour notre jeu : un format
permettant une run d'environ une demi-heure à une heure semble être le
standard, suffisamment long pour offrir un défi d'optimisation mais
assez court pour rester répétable.

Il faut toutefois nuancer : le graphique agrège toutes les runs
terminant le jeu, any\% et 100\% confondus, ainsi que des jeux de
longueurs très différentes. Les 46 minutes ne décrivent donc pas un
speedrun type mais la médiane d'un mélange hétérogène.

\newpage

\subsection{13. Quels sont les 15 pays qui concentrent le plus de runs
?}\label{quels-sont-les-15-pays-qui-concentrent-le-plus-de-runs}

Après avoir caractérisé la durée des runs, nous cherchons à localiser où
se trouve la communauté speedrun dans le monde : savoir d'où viennent
les joueurs nous indique les zones géographiques où concentrer notre
présense.

Nous imaginons que les États-Unis et les pays occidentaux anglophones
dominent largement, du fait de leurs grandes communautés de joueurs,
d'un bon accès à internet et du fait que la plateforme speedrun.com soit
anglophone.

\begin{verbatim}
## # A tibble: 63,108 x 1
##       lon
##     <dbl>
##  1 -77.0 
##  2  NA   
##  3  NA   
##  4   2.35
##  5 -77.0 
##  6 -77.0 
##  7 -75.7 
##  8 -77.0 
##  9  NA   
## 10 -77.0 
## # i 63,098 more rows
\end{verbatim}

\begin{verbatim}
## # A tibble: 63,108 x 3
##    platformName platform   lat
##    <chr>        <chr>    <dbl>
##  1 Atari 2600   o0644863  38.9
##  2 Atari 2600   o0644863  NA  
##  3 Atari 2600   o0644863  NA  
##  4 Atari 2600   o0644863  48.9
##  5 Atari 2600   o0644863  38.9
##  6 Atari 2600   o0644863  38.9
##  7 Atari 2600   o0644863  45.4
##  8 Atari 2600   o0644863  38.9
##  9 Atari 2600   o0644863  NA  
## 10 Atari 2600   o0644863  38.9
## # i 63,098 more rows
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-17-1.pdf}}

La carte confirme l'hypothèse et dessine une géographie nette : les
États-Unis dominent largement, suivis d'un bloc occidental dense
(Royaume-Uni, France, Allemagne et le reste de l'Europe de l'Ouest),
complété par le Brésil, le Canada, l'Australie et le Japon. L'activité
speedrun se concentre donc en Amérique du Nord et en Europe de l'Ouest.

Pour notre jeu, l'enseignement recoupe celui de l'étude des ventes :
c'est sur ces mêmes marchés occidentaux qu'il faudra concentrer nos
efforts de lancement et d'animation de communauté, avec un support en
anglais comme priorité évidente.

Une réserve toutefois : la localisation est déclarative et optionnelle
sur speedrun.com, la carte mesure les joueurs ayant renseigné leur
profil plutôt que la réalité, ce qui sur-représente sans doute les
communautés occidentales déjà bien intégrées à la plateforme.

\newpage

\subsection{14. Quels régions/pays concentrent le plus grand nombre de
runs
?}\label{quels-ruxe9gionspays-concentrent-le-plus-grand-nombre-de-runs}

La carte précédente montrait les pays un à un ; nous agrégeons ici par
région pour dégager la structure d'ensemble et voir comment les runs se
répartissent entre les grands blocs géographiques, puis à l'intérieur de
chacun. Cela précise le marché à viser : non plus pays par pays, mais à
l'échelle des continents.

Nous imaginons que les Amériques et l'Europe concentrent la grande
majorité des runs, dans la continuité de ce qu'a révélé la carte.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-18-1.pdf}}

Le treemap confirme la domination de deux blocs comparables, les
Amériques et l'Europe, le reste restant marginal. Il révèle surtout un
contraste de structure : les Amériques reposent presque entièrement sur
les États-Unis, tandis que l'Europe répartit son poids entre de nombreux
pays sans leader unique. Pour notre jeu, viser l'Amérique revient à
toucher une audience massive et homogène anglophone, là où l'Europe
constitue un marché fragmenté et multilingue.

\newpage

\subsection{Conclusion}\label{conclusion}

À travers nos analyses, nous avons dégagé plusieurs caractéristiques que
devrait réunir notre jeu pour maximiser ses chances d'être speedrunné :

\begin{itemize}
\tightlist
\item
  Une large audience : la popularité est un facteur déterminant, même si
  elle ne suffit pas à elle seule ;
\item
  Des mécaniques favorisant la rejouabilité : genres platformer ou
  course, avec des runs courtes et optimisables ;
\item
  Une durée maîtrisée : un format permettant des runs d'environ une
  demi-heure à une heure, assez longues pour offrir un défi
  d'optimisation mais assez courtes pour rester répétables ;
\item
  Un univers contemporain : un style proche des jeux des années 2010,
  pensé pour le streaming et le partage sur les réseaux sociaux ;
\item
  Une sortie sur PC : pour faciliter l'enregistrement et la publication
  de runs sur Speedrun.com.
\end{itemize}

L'étude de la localisation des joueurs précise par ailleurs le marché à
viser : la communauté speedrun est très concentrée en Amérique du Nord
et en Europe de l'Ouest, avec une nette domination anglophone. Le marché
américain offre une audience massive et homogène, tandis que l'Europe
constitue un marché fragmenté et multilingue ; un support en anglais
s'impose dans tous les cas comme priorité.

\newpage

\section{Couplage des données}\label{couplage-des-donnuxe9es}

Après avoir étudié séparément les ventes de jeux vidéo et l'activité des
communautés speedrun, nous cherchons désormais à comprendre s'il existe
un lien entre le succès commercial d'un jeu en Europe et son activité
sur Speedrun.com

\subsection{15. Existe-t-il un lien entre succès commercial en Europe et
activité speedrun
?}\label{existe-t-il-un-lien-entre-succuxe8s-commercial-en-europe-et-activituxe9-speedrun}

Nous cherchons ici à savoir si les jeux les plus vendus en Europe sont
aussi ceux qui génèrent le plus d'activité speedrun.

\begin{quote}
Les jeux les plus populaires commercialement devraient attirer davantage
de speedrunners, même si le gameplay et la rejouabilité semblent
également jouer un rôle important.
\end{quote}

Pour répondre à cette question, nous comparons les ventes européennes
(\texttt{EU\_Sales}) et le nombre de runs speedrun (\texttt{nb\_runs}) à
l'aide d'un nuage de points en échelle logarithmique.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-20-1.pdf}}

Le graphique met en évidence une tendance positive globale : les jeux
les plus vendus semblent également générer davantage de runs speedrun.
Cette relation reste toutefois relativement modérée et présente
plusieurs exceptions notables.

En effet, certains jeux très populaires commercialement possèdent une
activité speedrun limitée, tandis que d'autres jeux aux ventes plus
modestes développent des communautés particulièrement actives. Ces
résultats suggèrent que le succès commercial favorise la visibilité d'un
jeu, mais qu'il ne suffit pas à expliquer l'intérêt des speedrunners.

\newpage

\subsection{16. Quels jeux possèdent le meilleur ratio ``runs / ventes''
?}\label{quels-jeux-possuxe8dent-le-meilleur-ratio-runs-ventes}

Après avoir étudié le lien entre succès commercial et activité speedrun,
nous cherchons désormais à identifier les jeux qui génèrent une activité
speedrun particulièrement importante malgré des ventes plus limitées.

Nous formulons donc l'hypothèse suivante :

\begin{quote}
Certains jeux possèdent une activité speedrun particulièrement élevée
par rapport à leurs ventes grâce à leur forte rejouabilité, leur
gameplay technique ou leurs possibilités d'optimisation.
\end{quote}

Pour répondre à cette question, nous comparons le nombre de runs
speedrun (\texttt{nb\_runs}) aux ventes européennes
(\texttt{EU\_Sales}). Afin d'éviter les valeurs extrêmes, seuls les jeux
ayant au moins 0,5 million de ventes européennes et 20 runs ont été
conservés.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-21-1.pdf}}
Le graphique met en évidence plusieurs jeux possédant une activité
speedrun très importante par rapport à leurs ventes européennes.
\emph{Payday 2} se démarque nettement, suivi par des jeux comme
\emph{Wave Race 64}, \emph{Diddy Kong Racing} ou encore \emph{Sonic
Adventure 2 Battle}.

On observe également que plusieurs jeux présents dans ce classement
partagent certaines caractéristiques communes, notamment une forte
rejouabilité, un gameplay technique ou des mécaniques favorisant
l'optimisation des performances.

Ces résultats suggèrent que le succès d'un jeu auprès des speedrunners
ne dépend pas uniquement de son succès commercial. Même si la popularité
d'un jeu semble favoriser l'émergence d'une communauté active, le
gameplay et les possibilités offertes aux joueurs semblent également
jouer un rôle important dans l'intérêt porté au speedrun.

\textless\textless\textless\textless\textless\textless\textless{} HEAD
\newpage \#\# Est ce que genre les plus vendues sotn celles qu'on
speedrun le plus?

Comme dans les parties précedantes nous cherchons maintenant à savoir si
les genres les plus populaires commercialement sont également ceux qui
génèrent le plus d'activité speedrun.

\begin{quote}
Les genres les plus vendus devraient globalement être les plus
speedrunnés grâce à leur large base de joueurs et à leur popularité.
\end{quote}

Pour répondre à cette question, nous comparons les ventes mondiales
totales de chaque genre au nombre total de runs speedrun associés. Nous
utilisons un nuage de points (\emph{scatter plot}) afin d'étudier la
relation entre ces deux variables.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-22-1.pdf}}
Le graphique met en évidence une corrélation positive globale : les
genres les plus vendus, comme l'Action ou le Shooter, génèrent également
beaucoup d'activité speedrun. Cependant, certains genres s'écartent de
cette tendance. Les jeux de plateforme, par exemple, semblent
particulièrement surreprésentés dans le speedrun grâce à leurs
mécaniques optimisables et leur forte rejouabilité.

Ces résultats suggèrent donc que la popularité d'un genre favorise
l'activité speedrun, mais que certaines caractéristiques de gameplay
jouent également un rôle important.

\newpage

\subsection{Est ce que genre les plateformes vendues sotn celles qu'on
speedrun le
plus?}\label{est-ce-que-genre-les-plateformes-vendues-sotn-celles-quon-speedrun-le-plus}

Après avoir étudié les genres, nous cherchons maintenant à savoir si les
plateformes les plus populaires commercialement sont également celles
qui génèrent le plus d'activité speedrun.

\begin{quote}
Les plateformes les plus vendues devraient globalement être aussi les
plus speedrunnées. Nous nous attendons toutefois à une domination plus
marquée des plateformes Nintendo, historiquement très présentes dans la
communauté speedrun.
\end{quote}

Pour répondre à cette question, nous comparons les ventes européennes
totales de chaque plateforme au nombre total de runs speedrun associés.
Nous utilisons un nuage de points (\emph{scatter plot}) afin d'étudier
la relation entre ces deux variables.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-23-1.pdf}}
Le graphique confirme globalement notre hypothèse : les plateformes les
plus vendues génèrent généralement davantage d'activité speedrun. Les
consoles Sony dominent fortement en volume grâce au succès de la PS2, de
la PS1 ou encore de la PS4.

Cependant, Nintendo occupe une place particulière dans la communauté
speedrun. Des consoles comme la N64, la GameCube ou la SNES possèdent
une activité speedrun extrêmement élevée par rapport à leurs ventes
européennes. Cette surreprésentation semble liée aux nombreuses licences
emblématiques de Nintendo (\emph{Mario, Zelda, Metroid\ldots{}}),
historiquement très populaires dans le speedrun.

Ces résultats montrent donc que le succès commercial favorise l'activité
speedrun, mais que certaines plateformes développent également une forte
identité ``speedrun-compatible'' grâce à leur catalogue de jeux et à
leur culture communautaire.

=======
\textgreater\textgreater\textgreater\textgreater\textgreater\textgreater\textgreater{}
37d840435149025fde032e9bf0a4b74c29e1fa4f \newpage \#\# 17. Est ce que
genre les plus vendues sotn celles qu'on speedrun le plus?

\textless\textless\textless\textless\textless\textless\textless{} HEAD
Après avoir identifié certains jeux particulièrement populaires auprès
des speedrunners malgré des ventes plus modestes, nous cherchons
maintenant à mesurer l'investissement réel des différentes communautés
speedrun.

\begin{quote}
Les communautés les plus investies devraient présenter un nombre moyen
de runs par joueur particulièrement élevé.
\end{quote}

======= Comme dans les parties précedantes nous cherchons maintenant à
savoir si les genres les plus populaires commercialement sont également
ceux qui génèrent le plus d'activité speedrun.

\begin{quote}
Les genres les plus vendus devraient globalement être les plus
speedrunnés grâce à leur large base de joueurs et à leur popularité.
\end{quote}

Pour répondre à cette question, nous comparons les ventes mondiales
totales de chaque genre au nombre total de runs speedrun associés. Nous
utilisons un nuage de points (\emph{scatter plot}) afin d'étudier la
relation entre ces deux variables.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-24-1.pdf}}
Le graphique met en évidence une corrélation positive globale : les
genres les plus vendus, comme l'Action ou le Shooter, génèrent également
beaucoup d'activité speedrun. Cependant, certains genres s'écartent de
cette tendance. Les jeux de plateforme, par exemple, semblent
particulièrement surreprésentés dans le speedrun grâce à leurs
mécaniques optimisables et leur forte rejouabilité.

Ces résultats suggèrent donc que la popularité d'un genre favorise
l'activité speedrun, mais que certaines caractéristiques de gameplay
jouent également un rôle important.

\newpage

\subsection{18. Est ce que genre les plateformes vendues sotn celles
qu'on speedrun le
plus?}\label{est-ce-que-genre-les-plateformes-vendues-sotn-celles-quon-speedrun-le-plus-1}

Après avoir étudié les genres, nous cherchons maintenant à savoir si les
plateformes les plus populaires commercialement sont également celles
qui génèrent le plus d'activité speedrun.

\begin{quote}
Les plateformes les plus vendues devraient globalement être aussi les
plus speedrunnées. Nous nous attendons toutefois à une domination plus
marquée des plateformes Nintendo, historiquement très présentes dans la
communauté speedrun.
\end{quote}

Pour répondre à cette question, nous comparons les ventes européennes
totales de chaque plateforme au nombre total de runs speedrun associés.
Nous utilisons un nuage de points (\emph{scatter plot}) afin d'étudier
la relation entre ces deux variables.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-25-1.pdf}}
Le graphique confirme globalement notre hypothèse : les plateformes les
plus vendues génèrent généralement davantage d'activité speedrun. Les
consoles Sony dominent fortement en volume grâce au succès de la PS2, de
la PS1 ou encore de la PS4.

Cependant, Nintendo occupe une place particulière dans la communauté
speedrun. Des consoles comme la N64, la GameCube ou la SNES possèdent
une activité speedrun extrêmement élevée par rapport à leurs ventes
européennes. Cette surreprésentation semble liée aux nombreuses licences
emblématiques de Nintendo (\emph{Mario, Zelda, Metroid\ldots{}}),
historiquement très populaires dans le speedrun.

Ces résultats montrent donc que le succès commercial favorise l'activité
speedrun, mais que certaines plateformes développent également une forte
identité ``speedrun-compatible'' grâce à leur catalogue de jeux et à
leur culture communautaire.

\newpage

\subsection{19. Quels jeux ont la plus forte communauté speedrun par
rapport à leur nombre de joueurs
?}\label{quels-jeux-ont-la-plus-forte-communautuxe9-speedrun-par-rapport-uxe0-leur-nombre-de-joueurs}

Après avoir identifié certains jeux particulièrement populaires auprès
des speedrunners malgré des ventes plus modestes, nous cherchons
maintenant à mesurer l'investissement réel des différentes communautés
speedrun.

\begin{quote}
Les communautés les plus investies devraient présenter un nombre moyen
de runs par joueur particulièrement élevé.
\end{quote}

\begin{quote}
\begin{quote}
\begin{quote}
\begin{quote}
\begin{quote}
\begin{quote}
\begin{quote}
37d840435149025fde032e9bf0a4b74c29e1fa4f Pour répondre à cette question,
nous calculons le ratio suivant :
\end{quote}
\end{quote}
\end{quote}
\end{quote}
\end{quote}
\end{quote}
\end{quote}

\[
\text{Runs par joueur} = \frac{\text{Nombre total de runs}}{\text{Nombre de speedruners}}
\]

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-26-1.pdf}}
Le graphique met en évidence plusieurs jeux possédant des communautés
particulièrement investies. Des titres comme \emph{Gran Turismo 5},
\emph{Star Wars: Rogue Squadron} ou \emph{Urban Chaos} présentent un
nombre moyen de runs très élevé par joueur, suggérant un fort engagement
de leur communauté.

Ces résultats montrent que la taille d'une communauté ne suffit pas à
mesurer son implication : certains jeux possèdent des communautés plus
réduites mais beaucoup plus actives.

\newpage

\subsection{20. Les jeux les mieux notés attirent-ils davantage les
speedrunners
?}\label{les-jeux-les-mieux-notuxe9s-attirent-ils-davantage-les-speedrunners}

Après avoir étudié les genres les plus populaires auprès des
speedrunners, nous cherchons maintenant à savoir si les jeux les mieux
notés attirent également davantage d'activité speedrun.

\begin{quote}
Les jeux bénéficiant de bonnes notes critiques devraient globalement
générer plus de speedruns grâce à leur gameplay et leur rejouabilité.
\end{quote}

Pour répondre à cette question, nous comparons les notes critiques
(\texttt{Critic\_Score}) au nombre de runs speedrun (\texttt{nb\_runs})
à l'aide d'un nuage de points. Afin d'améliorer la lisibilité du
graphique, seuls les jeux possédant au moins 10 runs ont été conservés.

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-27-1.pdf}}

Le graphique montre une corrélation positive relativement faible entre
les scores critiques et l'activité speedrun. Les jeux mieux notés
semblent attirer davantage de speedrunners, mais plusieurs exceptions
importantes apparaissent.

Des jeux comme \emph{BioShock} ou \emph{Tekken 3} possèdent peu
d'activité speedrun malgré leurs excellentes notes, tandis que
\emph{Payday 2}, \emph{Destiny} ou \emph{Mirror's Edge} développent des
communautés très actives malgré des scores plus modestes.

Ces résultats suggèrent que la qualité critique joue un rôle, mais
qu'elle ne suffit pas à expliquer le succès d'un jeu auprès des
speedrunners.

\newpage

\subsection{21. Existe-t-il une ``recette parfaite'' du jeu
speedrunnable
?}\label{existe-t-il-une-recette-parfaite-du-jeu-speedrunnable}

Après avoir étudié séparément les ventes, les notes critiques, les
genres ou encore l'investissement des communautés, nous cherchons
désormais à identifier le profil moyen des jeux les plus populaires
auprès des speedrunners.

Cette question est particulièrement importante pour notre étude, car
elle permet de déterminer si les jeux possédant une communauté speedrun
active partagent certaines caractéristiques communes.

Nous formulons donc l'hypothèse suivante :

\begin{quote}
Les jeux les plus speedrunnés devraient présenter plusieurs
caractéristiques communes, notamment de bonnes évaluations critiques,
une forte rejouabilité, un grand nombre de catégories speedrun et des
communautés particulièrement actives.
\end{quote}

Pour répondre à cette question, nous comparons le profil moyen des jeux
appartenant au top 10\% des jeux les plus speedrunnés avec celui des
autres jeux. Nous utilisons un radar chart afin de visualiser
simultanément plusieurs variables : - les scores critiques et
utilisateurs ; - le nombre de joueurs speedrun ; - le nombre de
catégories speedrun ; - le nombre de plateformes ; - les ventes globales

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/figure-latex/unnamed-chunk-28-1.pdf}}

Le radar chart met en évidence plusieurs différences entre les jeux du
top 10\% speedrun et le reste des jeux du dataset.

On observe notamment que les jeux les plus speedrunnés possèdent
généralement : - de meilleures évaluations critiques et utilisateurs ; -
des communautés plus importantes ; - davantage de catégories speedrun ;
- ainsi qu'une présence sur un plus grand nombre de plateformes.

Les écarts les plus marqués concernent principalement le nombre de
catégories speedrun et la taille des communautés, ce qui semble suggérer
que la diversité des possibilités de jeu et d'optimisation joue un rôle
important dans l'intérêt des speedrunners.

Ces résultats montrent qu'il n'existe probablement pas une
caractéristique unique expliquant le succès d'un jeu auprès des
speedrunners. Le développement d'une communauté active semble plutôt
reposer sur une combinaison de plusieurs éléments : un gameplay
rejouable, des possibilités d'optimisation variées et une expérience
suffisamment riche pour encourager l'investissement des joueurs sur le
long terme.

\subsection{Conclusion}\label{conclusion-1}

Nos analyses montrent que le succès commercial ou les bonnes notes
critiques jouent un rôle, mais ne suffisent pas à expliquer l'engagement
des speedrunners. Certains blockbusters très populaires génèrent
finalement peu d'activité, tandis que des jeux plus confidentiels
développent des communautés extrêmement actives et investies.

Les résultats mettent surtout en évidence plusieurs caractéristiques
communes aux jeux les plus speedrunnés : - un gameplay dynamique et
technique ; - une forte rejouabilité ; - des mécaniques permettant
l'optimisation et la créativité ; - plusieurs catégories ou stratégies
de speedrun ; - une communauté engagée sur le long terme.

Concevoir un jeu adapté au speedrun ne consiste pas uniquement à
produire un jeu populaire, mais surtout un jeu profond, flexible et
agréable à maîtriser. Le speedrun apparaît donc avant tout comme une
question de game design et d'expérience de jeu, bien plus que de succès
commercial pur.

\end{document}
